### ISSUE TITLE
Create releases to be used with addon managers

### ISSUE THREAD

**Issue by DenL** [enolgor/wow-addon-tiptac#10]
Hi, thanks for your working maintaining this addon. This is more of a qol request.

If you were to create releases, people can use third party managers like wowup.io to automatically keep your version of tiptac updated instead of having to check back to this repo and updating manually.

Again thanks for your work!

**Comment by enolgor** [comment]
Nice suggestion working on it.

**Comment by enolgor** [comment]
Done. Updated README.md and also the version, using the schema of versions that the original author used, that is <year>.<month>.<day>.

Created also github workflow to automate zip release when a tag is pushed with the version.
