### ISSUE TITLE
For WQ embedded tooltip

### ISSUE THREAD

**Issue by hobulian** [enolgor/wow-addon-tiptac#11]
Your ApplyBackdrop function is pretty good but when it comes to WQ, embedded tooltip goes double lined so i made fix for that.

function tt:ApplyBackdrop(self)

local style = { bgFile = cfg.tipBackdropBG, edgeFile = cfg.tipBackdropEdge, tile = false, tileEdge = false, edgeSize = cfg.backdropEdgeSize, insets = { left = cfg.backdropInsets, right = cfg.backdropInsets, top = cfg.backdropInsets, bottom = cfg.backdropInsets }, backdropBorderColor = CreateColor(unpack(cfg.tipBorderColor)), backdropColor = CreateColor(unpack(cfg.tipColor)), }
 

**if self.IsEmbedded then style = GAME_TOOLTIP_BACKDROP_STYLE_EMBEDDED end**

--- Code from SharedXML/SharedTooltipTemplates.lua - SharedTooltip_SetBackdropStyle();

self:SetBackdrop(style);

self:SetBackdropBorderColor((style.backdropBorderColor or TOOLTIP_DEFAULT_COLOR)**:GetRGBA());**

elf:SetBackdropColor((style.backdropColor or TOOLTIP_DEFAULT_BACKGROUND_COLOR)**:GetRGBA());**

**Comment by hobulian** [comment]
GetRGBA can be anwser to 
Ticket "Unable to set a transparent 'Tip Background Color"

**Comment by enolgor** [comment]
Nice one. You fixed both issues 👍 

Updated and released thanks!

**Comment by alborland12** [comment]
Where should I add these lines?

**Comment by enolgor** [comment]
> Where should I add these lines?

As you can see the issue was closed and the code was added, It is included in the latest release.
