### ISSUE TITLE
Azerite and corruption border wouldn't show at those item's tooltip

### ISSUE THREAD

**Issue by hobulian** [enolgor/wow-addon-tiptac#18]
May this works

function tt:ApplyBackdrop(self)
	
	local style = {
		bgFile = cfg.tipBackdropBG,
		edgeFile = cfg.tipBackdropEdge,
		tile = false,
		tileEdge = false,
		edgeSize = cfg.backdropEdgeSize,
		insets = { left = cfg.backdropInsets, right = cfg.backdropInsets, top = cfg.backdropInsets, bottom = cfg.backdropInsets },
		backdropBorderColor = CreateColor(unpack(cfg.tipBorderColor)),
		backdropColor = CreateColor(unpack(cfg.tipColor)),
	}
	
	local _, itemLink = self:GetItem();
	if itemLink then
		if C_AzeriteEmpoweredItem.IsAzeriteEmpoweredItemByID(itemLink) or C_AzeriteItem.IsAzeriteItemByID(itemLink) then
			style.overlayAtlasTop = "AzeriteTooltip-Topper";
			style.overlayAtlasTopScale = .75;
			style.overlayAtlasTopYOffset = 1;
			style.overlayAtlasBottom = "AzeriteTooltip-Bottom";
			style.overlayAtlasBottomYOffset = 2;
			style.padding = { left = 3, right = 3, top = 3, bottom = 3 };
		elseif IsCorruptedItem(itemLink) then
			style.overlayAtlasTop = "Nzoth-tooltip-topper";
			style.overlayAtlasTopScale = .75;
			style.overlayAtlasTopYOffset = -2;
			style.padding = { left = 3, right = 3, top = 3, bottom = 3 };
		end
	end
		
	if self.IsEmbedded then style = GAME_TOOLTIP_BACKDROP_STYLE_EMBEDDED end

**Comment by enolgor** [comment]
Hi,
could you paste some pictures of before & after, and your configuration options (relevant ones, background and border). Since I'm not able to test and replicate your issue.
I will close issue #15 since it is a duplicate.

**Comment by enolgor** [comment]
@hobulian I made you a collaborator, so you can pull request with your changes anyway.
