### ISSUE TITLE
Inset tooltips clipping data inside parent tooltips

### ISSUE THREAD

**Issue by Thrayl** [enolgor/wow-addon-tiptac#6]
![image](https://user-images.githubusercontent.com/68885894/96369169-3071b880-11a4-11eb-9450-45fe4d9afdd2.png)

Mostly looking at WQ rewards. Possibly other areas that this is an issue also.

**Comment by Pingumania** [comment]
Add this line to the top of the function tt:ApplyBackdrop(tip)
```lua
if not tip or (tip.IsEmbedded or not tip.SetBackdrop) or tip:IsForbidden() then return end
```

**Comment by enolgor** [comment]
Awesome, works perfectly. Thanks for your time @frumpymoons I have limited time to look into the code and you are helping a lot!
I credit you in the code and commits, but you can make a PR with your fixes and I will merge them.
